# Netlify deployment configuration

[build]
  command = "npm install --include=optional --force && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "potrace"]
  included_files = ["node_modules/sharp/**", "node_modules/potrace/**"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"